import type { ComponentProps, ReactElement } from 'react';

import {
  Add01Icon,
  AddCircleIcon,
  AddSquareIcon,
  Alert01Icon,
  AppleIcon,
  ArchiveIcon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  ArrowUpRight01Icon,
  AtIcon,
  Attachment01Icon,
  Bookmark01Icon,
  Building03Icon,
  Calendar03Icon,
  Cancel01Icon,
  CancelCircleIcon,
  ChartIncreaseIcon,
  CheckIcon,
  CheckmarkCircle02Icon,
  ClipboardIcon,
  Clock01Icon,
  CloudIcon,
  CodeIcon,
  Comment01Icon,
  ComputerIcon,
  Copy01Icon,
  CreditCardIcon,
  CrownIcon,
  DatabaseIcon,
  Delete02Icon,
  DollarCircleIcon,
  Download01Icon,
  EyeIcon,
  FavouriteIcon,
  File01Icon,
  File02Icon,
  FileAddIcon,
  FileCodeIcon,
  FilterHorizontalIcon,
  FireIcon,
  Flag01Icon,
  FlashIcon,
  FloppyDiskIcon,
  Folder01Icon,
  FolderAddIcon,
  FolderOpenIcon,
  GitForkIcon,
  GithubIcon,
  GitlabIcon,
  Globe02Icon,
  GoogleIcon,
  GridViewIcon,
  HardDriveIcon,
  HelpCircleIcon,
  Home01Icon,
  Image01Icon,
  InboxIcon,
  InformationCircleIcon,
  Invoice01Icon,
  KeyboardIcon,
  LaptopIcon,
  LeftToRightListBulletIcon,
  Link01Icon,
  LinkedinIcon,
  LockIcon,
  Mail01Icon,
  MasterCardIcon,
  Megaphone01Icon,
  Menu01Icon,
  Mic01Icon,
  MicOff01Icon,
  Moon02Icon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  Notification01Icon,
  NotificationOff01Icon,
  NotionIcon,
  PackageIcon,
  PaintBoardIcon,
  PaypalIcon,
  PencilEdit01Icon,
  PinIcon,
  PlayIcon,
  Plug01Icon,
  PowerIcon,
  QrCodeIcon,
  QuoteUpIcon,
  ReceiptDollarIcon,
  RedoIcon,
  RefreshIcon,
  Rocket01Icon,
  ScissorIcon,
  Search01Icon,
  SecurityCheckIcon,
  ServerStack01Icon,
  Settings01Icon,
  ShoppingBag01Icon,
  ShoppingCart01Icon,
  ShuffleIcon,
  SlackIcon,
  SmartPhone01Icon,
  SparklesIcon,
  SquareUnlock01Icon,
  StarIcon,
  Sun01Icon,
  Tag01Icon,
  Target02Icon,
  TextAlignCenterIcon,
  TextAlignJustifyCenterIcon,
  TextAlignLeftIcon,
  TextAlignRightIcon,
  TextBoldIcon,
  TextItalicIcon,
  TextStrikethroughIcon,
  TextUnderlineIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  UndoIcon,
  UnfoldMoreIcon,
  Upload01Icon,
  UserEdit01Icon,
  UserGroupIcon,
  UserIcon,
  UserSettings01Icon,
  Video01Icon,
  ViewOffIcon,
  VolumeHighIcon,
  VolumeOffIcon,
  Wallet01Icon,
  Wrench01Icon,
} from '@aero/ui/icons';
import { HugeiconsIcon, type IconSvgElement } from '@aero/ui/icons';

const icons: Record<string, IconSvgElement> = {
  'add-circle-linear': AddCircleIcon,
  apple: AppleIcon,
  archive: ArchiveIcon,
  'alt-arrow-down-linear': ArrowDown01Icon,
  'brand-apple-filled': AppleIcon,
  'alt-arrow-right-linear': ArrowRight01Icon,
  'arrow-down': ArrowDown01Icon,
  'arrow-down-linear': ArrowDown01Icon,
  'arrow-left': ArrowLeft01Icon,
  'arrow-right': ArrowRight01Icon,
  'arrow-up': ArrowUp01Icon,
  'arrow-up-linear': ArrowUp01Icon,
  'arrow-right-from-square': ArrowUpRight01Icon,
  'arrow-uturn-ccw-left': UndoIcon,
  'arrow-uturn-cw-right': RedoIcon,
  at: AtIcon,
  bars: Menu01Icon,
  bell: Notification01Icon,
  bold: TextBoldIcon,
  'bolt-linear': FlashIcon,
  bookmark: Bookmark01Icon,
  box: PackageIcon,
  braces: CodeIcon,
  calendar: Calendar03Icon,
  'caret-right': ArrowRight01Icon,
  check: CheckIcon,
  'check-circle-bold': CheckmarkCircle02Icon,
  'chevron-down': ArrowDown01Icon,
  'chevron-left': ArrowLeft01Icon,
  'chevron-right': ArrowRight01Icon,
  'chevron-up': ArrowUp01Icon,
  'chevrons-expand-vertical': UnfoldMoreIcon,
  circle: HelpCircleIcon,
  'circle-check': CheckmarkCircle02Icon,
  'circle-check-big': CheckmarkCircle02Icon,
  'circle-dollar': DollarCircleIcon,
  'circle-fill': HelpCircleIcon,
  'circle-dashed': HelpCircleIcon,
  'circle-info': InformationCircleIcon,
  'circle-question': HelpCircleIcon,
  'circle-xmark': CancelCircleIcon,
  'circle-xmark-fill': CancelCircleIcon,
  clock: Clock01Icon,
  cloud: CloudIcon,
  'code-fork': GitForkIcon,
  component: GridViewIcon,
  copy: Copy01Icon,
  download: Download01Icon,
  ellipsis: MoreHorizontalIcon,
  'ellipsis-vertical': MoreVerticalIcon,
  envelope: Mail01Icon,
  eye: EyeIcon,
  'expo-icon': CodeIcon,
  'file-code-2': FileCodeIcon,
  'file-text': File02Icon,
  'floppy-disk': FloppyDiskIcon,
  folder: Folder01Icon,
  'folder-open': FolderOpenIcon,
  gear: Settings01Icon,
  'gallery-outline': Image01Icon,
  github: GithubIcon,
  'github-icon': GithubIcon,
  google: GoogleIcon,
  'google-icon': GoogleIcon,
  globe: Globe02Icon,
  'global-linear': Globe02Icon,
  heart: FavouriteIcon,
  'heart-bold': FavouriteIcon,
  'heart-fill': FavouriteIcon,
  italic: TextItalicIcon,
  'fire-linear': FireIcon,
  'hard-drive': HardDriveIcon,
  'letter-linear': Mail01Icon,
  'list-ul': LeftToRightListBulletIcon,
  'list-filter': FilterHorizontalIcon,
  linkedin: LinkedinIcon,
  'linkedin-icon': LinkedinIcon,
  'logo-apple': AppleIcon,
  lock: LockIcon,
  'lock-open': SquareUnlock01Icon,
  microphone: Mic01Icon,
  mastercard: MasterCardIcon,
  'menu-dots-bold': MoreHorizontalIcon,
  monitor: ComputerIcon,
  moon: Moon02Icon,
  'moon-linear': Moon02Icon,
  paperclip: Attachment01Icon,
  'palette-linear': PaintBoardIcon,
  pencil: PencilEdit01Icon,
  'person-gear': UserSettings01Icon,
  paypal: PaypalIcon,
  'baseline-paypal': PaypalIcon,
  person: UserIcon,
  persons: UserGroupIcon,
  picture: Image01Icon,
  pin: PinIcon,
  play: PlayIcon,
  'planet-earth': Globe02Icon,
  'play-16-solid': PlayIcon,
  'plug-connection': Plug01Icon,
  plus: Add01Icon,
  'qr-code': QrCodeIcon,
  quote: QuoteUpIcon,
  refresh: RefreshIcon,
  rocket: Rocket01Icon,
  scissors: ScissorIcon,
  'server-square-linear': ServerStack01Icon,
  search: Search01Icon,
  'settings-linear': Settings01Icon,
  'shopping-bag': ShoppingBag01Icon,
  'cart-large-2-linear': ShoppingCart01Icon,
  shuffle: ShuffleIcon,
  'square-article': File02Icon,
  'square-plus': AddSquareIcon,
  sparkles: SparklesIcon,
  star: StarIcon,
  'star-linear': StarIcon,
  'star-fill': StarIcon,
  strikethrough: TextStrikethroughIcon,
  sun: Sun01Icon,
  'text-align-center': TextAlignCenterIcon,
  'text-align-justify': TextAlignJustifyCenterIcon,
  'text-align-left': TextAlignLeftIcon,
  'text-align-right': TextAlignRightIcon,
  'target-linear': Target02Icon,
  'thumbs-down': ThumbsDownIcon,
  'thumbs-up': ThumbsUpIcon,
  'trash-2': Delete02Icon,
  'trash-bin': Delete02Icon,
  'trash-bin-trash-linear': Delete02Icon,
  tray: InboxIcon,
  'triangle-exclamation': Alert01Icon,
  underline: TextUnderlineIcon,
  user: UserIcon,
  'users-group-rounded-linear': UserGroupIcon,
  video: Video01Icon,
  wallet: Wallet01Icon,
  'layout-cells-large': GridViewIcon,
  'layout-columns-3': GridViewIcon,
  'social-linkedin': LinkedinIcon,
  visa: CreditCardIcon,
  'visa-logo-solid': CreditCardIcon,
  wrench: Wrench01Icon,
  'arrow-up-from-line': Upload01Icon,
  'arrows-rotate-left': RefreshIcon,
  'chart-column': GridViewIcon,
  'cloud-linear': CloudIcon,
  'cloud-outline': CloudIcon,
  comment: Comment01Icon,
  'credit-card': CreditCardIcon,
  'dollar-minimalistic-linear': DollarCircleIcon,
  file: File01Icon,
  gitlab: GitlabIcon,
  house: Home01Icon,
  inbox: InboxIcon,
  'key-linear': LockIcon,
  'layout-dashboard': GridViewIcon,
  linear: CodeIcon,
  'lock-password-outline': LockIcon,
  magnifier: Search01Icon,
  'master-card': MasterCardIcon,
  'message-circle': Comment01Icon,
  notion: NotionIcon,
  'notification-unread-outline': Notification01Icon,
  receipt: ReceiptDollarIcon,
  settings: Settings01Icon,
  'shield-keyhole-outline': LockIcon,
  'slack-icon': SlackIcon,
  'tag-price-linear': Tag01Icon,
  'user-linear': UserIcon,
  'user-plus-linear': UserGroupIcon,
  users: UserGroupIcon,
  'bell-fill': Notification01Icon,
  'bell-linear': Notification01Icon,
  'bell-slash': NotificationOff01Icon,
  'bill-list-linear': Invoice01Icon,
  'bookmark-fill': Bookmark01Icon,
  'buildings-outline': Building03Icon,
  clipboard: ClipboardIcon,
  'crown-outline': CrownIcon,
  'database-outline': DatabaseIcon,
  'eye-slash': ViewOffIcon,
  'file-plus-2': FileAddIcon,
  flag: Flag01Icon,
  'folder-open-linear': FolderOpenIcon,
  'folder-plus': FolderAddIcon,
  'graph-up-outline': ChartIncreaseIcon,
  keyboard: KeyboardIcon,
  'laptop-linear': LaptopIcon,
  link: Link01Icon,
  'lock-outline': LockIcon,
  'megaphone-linear': Megaphone01Icon,
  'microphone-slash': MicOff01Icon,
  'monitor-linear': ComputerIcon,
  palette: PaintBoardIcon,
  'pen-linear': PencilEdit01Icon,
  'pin-fill': PinIcon,
  power: PowerIcon,
  'rocket-outline': Rocket01Icon,
  'server-outline': ServerStack01Icon,
  'shield-check-linear': SecurityCheckIcon,
  'smartphone-linear': SmartPhone01Icon,
  'user-round-pen': UserEdit01Icon,
  'volume-fill': VolumeHighIcon,
  'volume-slash-fill': VolumeOffIcon,
  x: Cancel01Icon,
};

export interface IconProps extends Omit<
  ComponentProps<typeof HugeiconsIcon>,
  'icon' | 'size'
> {
  height?: number | string;
  icon: string;
  inline?: boolean;
  width?: number | string;
}

export function Icon({
  height,
  icon,
  inline: _inline,
  width,
  ...props
}: IconProps): ReactElement {
  const name = icon.includes(':') ? icon.slice(icon.indexOf(':') + 1) : icon;
  const selected = icons[name] ?? File01Icon;
  const dimension = Number(width ?? height ?? 16);
  const fill = name.endsWith('-fill') ? 'currentColor' : 'none';

  return (
    <HugeiconsIcon
      aria-hidden={props['aria-label'] ? undefined : true}
      fill={fill}
      icon={selected}
      size={Number.isFinite(dimension) ? dimension : 16}
      strokeWidth={2}
      {...props}
    />
  );
}
