// components/theme-labels.ts
import { ColorTheme } from '@/app/providers/theme';

export const THEME_LABELS: Record<ColorTheme, string> = {
  aero: 'Aero',
  amoled: 'Amoled',
  aura: 'Aura',
  ayu: 'Ayu',
  carbonfox: 'Carbonfox',
  catppuccin: 'Catppuccin',
  cursor: 'Cursor',
  dracula: 'Dracula',
  'fields-of-the-shire': 'Fields of the Shire',
  flexoki: 'Flexoki',
  github: 'GitHub',
  gruvbox: 'Gruvbox',
  jetbrains: 'JetBrains',
  kanagawa: 'Kanagawa',
  'lucent-orng': 'Lucent Orng',
  mono: 'Mono',
  'mono-plus': 'Mono Plus',
  monokai: 'Monokai',
  nightowl: 'Night Owl',
  nord: 'Nord',
  'oc-2': 'OC-2',
  onedarkpro: 'OneDark Pro',
  orng: 'Orng',
  rosepine: 'Rosé Pine',
  shadesofpurple: 'Shades of Purple',
  solarized: 'Solarized',
  tokyonight: 'Tokyo Night',
  vesper: 'Vesper',
  vitesse: 'Vitesse',
  zenburn: 'Zenburn',
};
